<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionRoleSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		foreach ($this->getPermissionRoleMap() as $permissionRole) {
			DB::table('permission_role')->insert($permissionRole);
		}
	}

	public function getPermissionRoleMap()
	{
		return [
			["permission_label" => "location:all:edit", "role_label" => "owner"],
			["permission_label" => "location:all:edit", "role_label" => "admin"],
			["permission_label" => "location:all:remove", "role_label" => "owner"],
			["permission_label" => "location:all:remove", "role_label" => "admin"],
			["permission_label" => "location:all:search", "role_label" => "owner"],
			["permission_label" => "location:all:search", "role_label" => "admin"],
			["permission_label" => "location:all:search", "role_label" => "editor"],
			["permission_label" => "location:all:search", "role_label" => "writer"],
			["permission_label" => "location:all:view", "role_label" => "owner"],
			["permission_label" => "location:all:view", "role_label" => "admin"],
			["permission_label" => "location:all:view", "role_label" => "editor"],
			["permission_label" => "location:all:view", "role_label" => "writer"],
			["permission_label" => "location:all:view", "role_label" => "observer"],
			["permission_label" => "location:create", "role_label" => "owner"],
			["permission_label" => "location:create", "role_label" => "admin"],
			["permission_label" => "location:create", "role_label" => "editor"],
			["permission_label" => "location:create", "role_label" => "writer"],
			["permission_label" => "location:own:edit", "role_label" => "owner"],
			["permission_label" => "location:own:edit", "role_label" => "admin"],
			["permission_label" => "location:own:edit", "role_label" => "editor"],
			["permission_label" => "location:own:edit", "role_label" => "writer"],
			["permission_label" => "location:own:remove", "role_label" => "owner"],
			["permission_label" => "location:own:remove", "role_label" => "admin"],
			["permission_label" => "location:own:remove", "role_label" => "editor"],
			["permission_label" => "location:own:remove", "role_label" => "writer"],
			["permission_label" => "members:add", "role_label" => "owner"],
			["permission_label" => "members:add", "role_label" => "admin"],
			["permission_label" => "members:add-admin", "role_label" => "owner"],
			["permission_label" => "members:edit-admin", "role_label" => "owner"],
			["permission_label" => "members:edit", "role_label" => "owner"],
			["permission_label" => "members:edit", "role_label" => "admin"],
			["permission_label" => "members:remove", "role_label" => "owner"],
			["permission_label" => "members:remove", "role_label" => "admin"],
			["permission_label" => "members:remove-admin", "role_label" => "owner"],
			["permission_label" => "members:edit-owner", "role_label" => "owner"],
			["permission_label" => "payment:all:change-division", "role_label" => "owner"],
			["permission_label" => "payment:all:change-division", "role_label" => "admin"],
			["permission_label" => "payment:all:edit", "role_label" => "owner"],
			["permission_label" => "payment:all:edit", "role_label" => "admin"],
			["permission_label" => "payment:all:remove", "role_label" => "owner"],
			["permission_label" => "payment:all:remove", "role_label" => "admin"],
			["permission_label" => "payment:create", "role_label" => "owner"],
			["permission_label" => "payment:create", "role_label" => "admin"],
			["permission_label" => "payment:create", "role_label" => "editor"],
			["permission_label" => "payment:own:change-division", "role_label" => "owner"],
			["permission_label" => "payment:own:change-division", "role_label" => "admin"],
			["permission_label" => "payment:own:change-division", "role_label" => "editor"],
			["permission_label" => "payment:own:edit", "role_label" => "owner"],
			["permission_label" => "payment:own:edit", "role_label" => "admin"],
			["permission_label" => "payment:own:edit", "role_label" => "editor"],
			["permission_label" => "payment:own:remove", "role_label" => "owner"],
			["permission_label" => "payment:own:remove", "role_label" => "admin"],
			["permission_label" => "payment:own:remove", "role_label" => "editor"],
			["permission_label" => "payment:all:view", "role_label" => "owner"],
			["permission_label" => "payment:all:view", "role_label" => "admin"],
			["permission_label" => "payment:all:view", "role_label" => "editor"],
			["permission_label" => "payment:all:view", "role_label" => "writer"],
			["permission_label" => "payment:all:view", "role_label" => "observer"],
			["permission_label" => "plan:all:edit", "role_label" => "owner"],
			["permission_label" => "plan:all:edit", "role_label" => "admin"],
			["permission_label" => "plan:all:link-location", "role_label" => "owner"],
			["permission_label" => "plan:all:link-location", "role_label" => "admin"],
			["permission_label" => "plan:all:link-poi", "role_label" => "owner"],
			["permission_label" => "plan:all:link-poi", "role_label" => "admin"],
			["permission_label" => "plan:all:remove", "role_label" => "owner"],
			["permission_label" => "plan:all:remove", "role_label" => "admin"],
			["permission_label" => "plan:all:unlink-location", "role_label" => "owner"],
			["permission_label" => "plan:all:unlink-location", "role_label" => "admin"],
			["permission_label" => "plan:all:unlink-poi", "role_label" => "owner"],
			["permission_label" => "plan:all:unlink-poi", "role_label" => "admin"],
			["permission_label" => "plan:create", "role_label" => "owner"],
			["permission_label" => "plan:create", "role_label" => "admin"],
			["permission_label" => "plan:create", "role_label" => "editor"],
			["permission_label" => "plan:own:edit", "role_label" => "owner"],
			["permission_label" => "plan:own:edit", "role_label" => "admin"],
			["permission_label" => "plan:own:edit", "role_label" => "editor"],
			["permission_label" => "plan:own:link-location", "role_label" => "owner"],
			["permission_label" => "plan:own:link-location", "role_label" => "admin"],
			["permission_label" => "plan:own:link-location", "role_label" => "editor"],
			["permission_label" => "plan:own:link-poi", "role_label" => "owner"],
			["permission_label" => "plan:own:link-poi", "role_label" => "admin"],
			["permission_label" => "plan:own:link-poi", "role_label" => "editor"],
			["permission_label" => "plan:own:remove", "role_label" => "owner"],
			["permission_label" => "plan:own:remove", "role_label" => "admin"],
			["permission_label" => "plan:own:remove", "role_label" => "editor"],
			["permission_label" => "plan:own:unlink-location", "role_label" => "owner"],
			["permission_label" => "plan:own:unlink-location", "role_label" => "admin"],
			["permission_label" => "plan:own:unlink-location", "role_label" => "editor"],
			["permission_label" => "plan:own:unlink-poi", "role_label" => "owner"],
			["permission_label" => "plan:own:unlink-poi", "role_label" => "admin"],
			["permission_label" => "plan:own:unlink-poi", "role_label" => "editor"],
			["permission_label" => "poi:all:search", "role_label" => "owner"],
			["permission_label" => "poi:all:search", "role_label" => "admin"],
			["permission_label" => "poi:all:search", "role_label" => "editor"],
			["permission_label" => "poi:all:search", "role_label" => "writer"],
			["permission_label" => "poi:all:search", "role_label" => "observer"],
			["permission_label" => "poi:all:view", "role_label" => "owner"],
			["permission_label" => "poi:all:view", "role_label" => "admin"],
			["permission_label" => "poi:all:view", "role_label" => "editor"],
			["permission_label" => "poi:all:view", "role_label" => "writer"],
			["permission_label" => "poi:all:view", "role_label" => "observer"],
			["permission_label" => "report:all:edit", "role_label" => "owner"],
			["permission_label" => "report:all:edit", "role_label" => "admin"],
			["permission_label" => "report:all:link-plan", "role_label" => "owner"],
			["permission_label" => "report:all:link-plan", "role_label" => "admin"],
			["permission_label" => "report:all:remove", "role_label" => "owner"],
			["permission_label" => "report:all:remove", "role_label" => "admin"],
			["permission_label" => "report:all:unlink-plan", "role_label" => "owner"],
			["permission_label" => "report:all:unlink-plan", "role_label" => "admin"],
			["permission_label" => "report:all:view", "role_label" => "owner"],
			["permission_label" => "report:all:view", "role_label" => "admin"],
			["permission_label" => "report:all:view", "role_label" => "editor"],
			["permission_label" => "report:all:view", "role_label" => "writer"],
			["permission_label" => "report:all:view", "role_label" => "observer"],
			["permission_label" => "report:create", "role_label" => "owner"],
			["permission_label" => "report:create", "role_label" => "admin"],
			["permission_label" => "report:create", "role_label" => "editor"],
			["permission_label" => "report:own:edit", "role_label" => "owner"],
			["permission_label" => "report:own:edit", "role_label" => "admin"],
			["permission_label" => "report:own:edit", "role_label" => "editor"],
			["permission_label" => "report:own:link-plan", "role_label" => "owner"],
			["permission_label" => "report:own:link-plan", "role_label" => "admin"],
			["permission_label" => "report:own:link-plan", "role_label" => "editor"],
			["permission_label" => "report:own:remove", "role_label" => "owner"],
			["permission_label" => "report:own:remove", "role_label" => "admin"],
			["permission_label" => "report:own:remove", "role_label" => "editor"],
			["permission_label" => "report:own:unlink-plan", "role_label" => "owner"],
			["permission_label" => "report:own:unlink-plan", "role_label" => "admin"],
			["permission_label" => "report:own:unlink-plan", "role_label" => "editor"],
			["permission_label" => "section:all:edit", "role_label" => "owner"],
			["permission_label" => "section:all:edit", "role_label" => "admin"],
			["permission_label" => "section:all:link-location", "role_label" => "owner"],
			["permission_label" => "section:all:link-location", "role_label" => "admin"],
			["permission_label" => "section:all:link-payment", "role_label" => "owner"],
			["permission_label" => "section:all:link-payment", "role_label" => "admin"],
			["permission_label" => "section:all:link-poi", "role_label" => "owner"],
			["permission_label" => "section:all:link-poi", "role_label" => "admin"],
			["permission_label" => "section:all:remove", "role_label" => "owner"],
			["permission_label" => "section:all:remove", "role_label" => "admin"],
			["permission_label" => "section:all:unlink-location", "role_label" => "owner"],
			["permission_label" => "section:all:unlink-location", "role_label" => "admin"],
			["permission_label" => "section:all:unlink-payment", "role_label" => "owner"],
			["permission_label" => "section:all:unlink-payment", "role_label" => "admin"],
			["permission_label" => "section:all:unlink-poi", "role_label" => "owner"],
			["permission_label" => "section:all:unlink-poi", "role_label" => "admin"],
			["permission_label" => "section:all:view", "role_label" => "owner"],
			["permission_label" => "section:all:view", "role_label" => "admin"],
			["permission_label" => "section:all:view", "role_label" => "editor"],
			["permission_label" => "section:all:view", "role_label" => "writer"],
			["permission_label" => "section:all:view", "role_label" => "observer"],
			["permission_label" => "section:create", "role_label" => "owner"],
			["permission_label" => "section:create", "role_label" => "admin"],
			["permission_label" => "section:create", "role_label" => "editor"],
			["permission_label" => "section:create", "role_label" => "writer"],
			["permission_label" => "section:own:edit", "role_label" => "owner"],
			["permission_label" => "section:own:edit", "role_label" => "admin"],
			["permission_label" => "section:own:edit", "role_label" => "editor"],
			["permission_label" => "section:own:edit", "role_label" => "writer"],
			["permission_label" => "section:own:link-location", "role_label" => "owner"],
			["permission_label" => "section:own:link-location", "role_label" => "admin"],
			["permission_label" => "section:own:link-location", "role_label" => "editor"],
			["permission_label" => "section:own:link-location", "role_label" => "writer"],
			["permission_label" => "section:own:link-payment", "role_label" => "owner"],
			["permission_label" => "section:own:link-payment", "role_label" => "admin"],
			["permission_label" => "section:own:link-payment", "role_label" => "editor"],
			["permission_label" => "section:own:link-poi", "role_label" => "owner"],
			["permission_label" => "section:own:link-poi", "role_label" => "admin"],
			["permission_label" => "section:own:link-poi", "role_label" => "editor"],
			["permission_label" => "section:own:link-poi", "role_label" => "writer"],
			["permission_label" => "section:own:remove", "role_label" => "owner"],
			["permission_label" => "section:own:remove", "role_label" => "admin"],
			["permission_label" => "section:own:remove", "role_label" => "editor"],
			["permission_label" => "section:own:remove", "role_label" => "writer"],
			["permission_label" => "section:own:unlink-location", "role_label" => "owner"],
			["permission_label" => "section:own:unlink-location", "role_label" => "admin"],
			["permission_label" => "section:own:unlink-location", "role_label" => "editor"],
			["permission_label" => "section:own:unlink-location", "role_label" => "writer"],
			["permission_label" => "section:own:unlink-payment", "role_label" => "owner"],
			["permission_label" => "section:own:unlink-payment", "role_label" => "admin"],
			["permission_label" => "section:own:unlink-payment", "role_label" => "editor"],
			["permission_label" => "section:own:unlink-poi", "role_label" => "owner"],
			["permission_label" => "section:own:unlink-poi", "role_label" => "admin"],
			["permission_label" => "section:own:unlink-poi", "role_label" => "editor"],
			["permission_label" => "section:own:unlink-poi", "role_label" => "writer"],
			["permission_label" => "trip:edit", "role_label" => "owner"],
			["permission_label" => "trip:edit", "role_label" => "admin"],
			["permission_label" => "trip:link-payment", "role_label" => "owner"],
			["permission_label" => "trip:link-payment", "role_label" => "admin"],
			["permission_label" => "trip:link-payment", "role_label" => "editor"],
			["permission_label" => "trip:remove", "role_label" => "owner"],
			["permission_label" => "trip:unlink-payment", "role_label" => "owner"],
			["permission_label" => "trip:unlink-payment", "role_label" => "admin"],
			["permission_label" => "trip:view", "role_label" => "owner"],
			["permission_label" => "trip:view", "role_label" => "admin"],
			["permission_label" => "trip:view", "role_label" => "editor"],
			["permission_label" => "trip:view", "role_label" => "writer"],
			["permission_label" => "trip:view", "role_label" => "observer"],
			["permission_label" => "visitors:add", "role_label" => "owner"],
			["permission_label" => "visitors:add", "role_label" => "admin"],
			["permission_label" => "visitors:remove", "role_label" => "owner"],
			["permission_label" => "visitors:remove", "role_label" => "admin"],
			["permission_label" => "visitors:update", "role_label" => "owner"],
			["permission_label" => "visitors:update", "role_label" => "admin"],
		];
	}
}
