<?php

namespace Columbo\Traits\Auth;

use Illuminate\Auth\Events\Registered;
use Illuminate\Foundation\Auth\RedirectsUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Validator;

// This trait has been copied and modified from the
// 	default Laravel make:auth scaffolding.
trait RegistersUsersWithToken
{
    use RedirectsUsers;

    /** @var String The token generated by the registration */
    private $token;

    /**
     * Show the application registration form.
     *
     * @return \Illuminate\Http\Response
     */
    public function showRegistrationForm()
    {
        return view('auth.register');
    }

    /**
     * Handle a registration request for the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function register(Request $request)
    {
        $validator = $this->validator($request->all());

        if ($validator->fails()) {
            return $this->validationFailed($validator);
        }

        event(new Registered($user = $this->create($request->all())));

        $this->token = $user->createToken($request->device_name)->plainTextToken;

        return $this->registered($request, $user)
                        ?: redirect($this->redirectPath());
    }

    protected function validationFailed(Validator $validator)
    {
        return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
    }

    /**
     * Get the token generated on registration.
     *
     * @return String
     */
    protected function getToken()
    {
    	return $this->token;
    }

    /**
     * Get the guard to be used during registration.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard();
    }

    /**
     * The user has been registered.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function registered(Request $request, $user)
    {
        //
    }
}
